### ISSUE TITLE
Copilot- Issue with configuring SSO for Web

### ISSUE THREAD

**Issue by MariamPaulachan** [microsoft/CopilotStudioSamples#151]
Hi Team,

I have referred this code to configure SSO in web copilot (https://github.com/microsoft/CopilotStudioSamples/blob/master/BuildYourOwnCanvasSamples/3.single-sign-on/index.html). Could you confirm why is there a step to login with the validation code, when single sign on is enabled? 
Also sharing screenshot for reference.

<img width="656" alt="Capture" src="https://github.com/microsoft/CopilotStudioSamples/assets/76100807/fe0de48f-28f3-401a-a929-b66f8423488c">

**Comment by adilei** [comment]
Hey Mariam, 

I can confirm that the code sample does work as expected when configured properly. I suggest your share any client side errors you are getting, as well as the configuration for your: 1. copilot app registration and 2. canvas app registration

**Comment by adilei** [comment]
Thanks Mariam. Already asked for this on the Copilot Studio Community, but for the benefit of anyone reading here, can you reproduce the issue using the (unmodified) sample provided in the docs? 

https://github.com/microsoft/CopilotStudioSamples/blob/master/BuildYourOwnCanvasSamples/3.single-sign-on/index.html

**Comment by adilei** [comment]
Hi Mariam,

Based on our conversation [here](https://powerusers.microsoft.com/t5/General/Copilot-Issue-with-configuring-SSO-for-Web/m-p/2513474/highlight/true#M7906) I am closing this issue.

As you reported:

1. The canvas app registration was missing permissions for the custom scope created for the copilot app registration
2. The token exchange URL should have been populated in the copilot authentication settings

**Comment by marcorocca1973** [comment]
Hi Adilei 
one question.... the correct behavior is that when I open the test html web page in a browser session already authenticated the chatbot not require the login; this is true?
