### ISSUE TITLE
[Implementation Guide] Import error: The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

### ISSUE THREAD

**Issue by UnremittingTerryWang** [microsoft/CopilotStudioSamples#154]
**Template version**: the version of number is available on the first slide, in the bottom left corner.
**Slide number(s)**: slides where your feedback applies to

**Detail your feedback and suggestions:**
Add details on your feedback on the implementation guide, or suggestions for new content or improvements.
When tried to import solution in Power Apps, got below error message:
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
![image](https://github.com/microsoft/CopilotStudioSamples/assets/33817781/1bb6f12a-18d7-4267-b1c0-99a79c444e03)

**Comment by HenryJammes** [comment]
Hi @UnremittingTerryWang

I'm sorry I'm not sure I understand what you're trying to do?
From the screenshot, it looks like you exported the full GitHub repo as a zip and then tried to import it as a solution?

Henry

**Comment by UnremittingTerryWang** [comment]
> Hi @UnremittingTerryWang
> 
> I'm sorry I'm not sure I understand what you're trying to do? From the screenshot, it looks like you exported the full GitHub repo as a zip and then tried to import it as a solution?
> 
> Henry

Hi Henry, 

Yes you are right. I was trying to import this zip file to PowerApps with following the steps mentioned in https://github.com/Flow-Joe/PowerVirtualAgentsSamples/blob/master/Templates/Employee%20FAQ/README.md
![image](https://github.com/microsoft/CopilotStudioSamples/assets/33817781/cef33141-15ed-4490-8856-610dcca2969b)

And got the error. Would you please share your suggestions about the error? Thanks a lot.

**Comment by HenryJammes** [comment]
I see, thank you @UnremittingTerryWang
I believe the zip file you're looking for is one of these: https://github.com/microsoft/CopilotStudioSamples/tree/master/Templates/Employee%20FAQ/Solutions
