### ISSUE TITLE
[Implementation Guide] I'm looking for a freelancer to implement this for my company's chatbot

### ISSUE THREAD

**Issue by nicolelynn4182** [microsoft/CopilotStudioSamples#155]
I am in way over my head with this project. I would love to hire someone, as a freelancer, to implement this solution for a chatbot that my company has deployed through Power Virtual Agent/Copilot Studio Chat (classic). The analytics that we get through PVA are not sufficient for our operations, so we would like to see the data through Power BI.

**Comment by HenryJammes** [comment]
Hi @nicolelynn4182,

We can't recommend freelancers or partners on this GitHub repository. The feedback we gather here is more about the samples themselves or about the implementation guide content.

Have you considered posting on the https://[aka.ms/CopilotStudioCommunity](https://aka.ms/CopilotStudioCommunity) forum? There may be Copilot Studio subject matter experts and freelancers willing to help you.

Henry
