### ISSUE TITLE
Issue: SharePoint SSO Component

### ISSUE THREAD

**Issue by davecope1982** [microsoft/CopilotStudioSamples#173]
Is it possible to add the newly created Copilot to other apps such as Teams?

**Comment by adilei** [comment]
Teams is available as a native channel, so you will not need the code sample for that.

To publish a custom copilot to Teams and provide Generative Answers over SharePoint you would have to set up authentication:

https://learn.microsoft.com/en-us/microsoft-copilot-studio/configuration-authentication-azure-ad
https://learn.microsoft.com/en-us/microsoft-copilot-studio/configure-sso-teams
