### ISSUE TITLE
Issue: SharePoint SSO Component Not showing up in

### ISSUE THREAD

**Issue by FHtwoday** [microsoft/CopilotStudioSamples#175]
I followed the step by step, tried it a few times now, but still the Chat bot does not appear on my sites. I have tried delete the app och upload it again, but after i added it to the sharepoint site it does not show.

Am i missing something?

**Comment by adilei** [comment]
You don't even get the chat button at the bottom of the page?

**Comment by adilei** [comment]
And the app on your site looks like below? i.e. says "added" with no error? Do you have any other site extensions loaded?

![image](https://github.com/microsoft/CopilotStudioSamples/assets/28257760/b3ef5d67-f7fa-40c4-9156-2913e24d51a1)

**Comment by FHtwoday** [comment]
Yes, no error and it says added. No other extensions loaded, completly new site.

**Comment by adilei** [comment]
Hmmm..not sure. Maybe share the sppkg file directly with me? adileibowitz@microsoft.com

**Comment by sosandumsft** [comment]
Hello, I've managed to see it on page but it's not doing anything. Opens the canvas and stays in Loading.
![image](https://github.com/microsoft/CopilotStudioSamples/assets/105270821/0504827d-ce51-4e86-9b10-729576cb1093)
Any idea what can be wrong ?

**Comment by adilei** [comment]
> Hello, I've managed to see it on page but it's not doing anything. Opens the canvas and stays in Loading. ![image](https://private-user-images.githubusercontent.com/105270821/309805763-0504827d-ce51-4e86-9b10-729576cb1093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIwMjAsIm5iZiI6MTcwOTYyMTcyMCwicGF0aCI6Ii8xMDUyNzA4MjEvMzA5ODA1NzYzLTA1MDQ4MjdkLWNlNTEtNGU4Ni05YjEwLTcyOTU3NmNiMTA5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNjU1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjNiNDIwODBlYzM3YjZlNGEyYjdhZGNjZGM2ZGFhODM0Yjc2MWNiZThkZTdjMGMyMWYwYTZmN2UxMDI5NjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E-jwMvrqvCesmlBQTIvi2w5YiaNuzB42rO_hU9pWV_Q) Any idea what can be wrong ?

Chatted internally - in your case some URIs were missing from Redirect URIs - correct?

**Comment by FHtwoday** [comment]
> Hmmm..not sure. Maybe share the sppkg file directly with me? [adileibowitz@microsoft.com](mailto:adileibowitz@microsoft.com)

Hi! 
Did you get my email last week?

**Comment by adilei** [comment]
> > Hmmm..not sure. Maybe share the sppkg file directly with me? [adileibowitz@microsoft.com](mailto:adileibowitz@microsoft.com)
> 
> Hi! Did you get my email last week?

Nope, possibly blocked? You can also just share your elements.xml, maybe that has a better chance of getting through.

**Comment by FHtwoday** [comment]
> > > Hmmm..not sure. Maybe share the sppkg file directly with me? [adileibowitz@microsoft.com](mailto:adileibowitz@microsoft.com)
> > 
> > 
> > Hi! Did you get my email last week?
> 
> Nope, possibly blocked? You can also just share your elements.xml, maybe that has a better chance of getting through.

Tried it now, hope it gets through! :)

**Comment by adilei** [comment]
> > > > Hmmm..not sure. Maybe share the sppkg file directly with me? [adileibowitz@microsoft.com](mailto:adileibowitz@microsoft.com)
> > > 
> > > 
> > > Hi! Did you get my email last week?
> > 
> > 
> > Nope, possibly blocked? You can also just share your elements.xml, maybe that has a better chance of getting through.
> 
> Tried it now, hope it gets through! :)

It did, and your "authority" property is wrong. Take a look at the guide for a reference.

**Comment by adilei** [comment]
@FHtwoday there's a new script in the sample that allows you to upload the component first, and then configure. I think having to wrestle with elements.xml created too many issues. 

https://github.com/microsoft/CopilotStudioSamples/blob/master/SharePointSSOComponent/SETUP.md#step-4--upload-the-component-to-sharepoint

**Comment by Penjilia** [comment]
> > Hello, I've managed to see it on page but it's not doing anything. Opens the canvas and stays in Loading. ![image](https://private-user-images.githubusercontent.com/105270821/309805763-0504827d-ce51-4e86-9b10-729576cb1093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIwMjAsIm5iZiI6MTcwOTYyMTcyMCwicGF0aCI6Ii8xMDUyNzA4MjEvMzA5ODA1NzYzLTA1MDQ4MjdkLWNlNTEtNGU4Ni05YjEwLTcyOTU3NmNiMTA5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNjU1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjNiNDIwODBlYzM3YjZlNGEyYjdhZGNjZGM2ZGFhODM0Yjc2MWNiZThkZTdjMGMyMWYwYTZmN2UxMDI5NjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E-jwMvrqvCesmlBQTIvi2w5YiaNuzB42rO_hU9pWV_Q) Any idea what can be wrong ?
> 
> Chatted internally - in your case some URIs were missing from Redirect URIs - correct?

Having this same issue where the bot is showing, however, just loading, any suggestions for the possible fix?

**Comment by stegt3** [comment]
Hi - having a similar issue where if we deploy the default sppkg file to our sharepoint page, the button shows up, although not configured.  If we try to run the script, the script will complete, but then the button disappears from the page completely.  We have also tried building the package in VS code after updating the elements.xml file, and uploading to sharepoint - but the button still does not appear.  At a loss what could be happening - the properties should be in the same format as suggested.  Thanks.

**Comment by adilei** [comment]
> Hi - having a similar issue where if we deploy the default sppkg file to our sharepoint page, the button shows up, although not configured. If we try to run the script, the script will complete, but then the button disappears from the page completely. We have also tried building the package in VS code after updating the elements.xml file, and uploading to sharepoint - but the button still does not appear. At a loss what could be happening - the properties should be in the same format as suggested. Thanks.

Can you open a new issue?

**Comment by adilei** [comment]
Closed due to inactivity
