### ISSUE TITLE
Login button appears on SharePoint chat bot window Issue: SharePoint SSO Component

### ISSUE THREAD

**Issue by vikassharmaatl** [microsoft/CopilotStudioSamples#178]
the login button appears on the chatbot window in SharePoint. I have to paste the token to continue. Any reason why this would happen .
The login button does not appear in the test chat window within Copilot Studio.

**Comment by adilei** [comment]
The login button appears when the component does not send the custom scope expected by the copilot. Make sure the same custom scope is populated both in elements.xml and in your copilot security settings.

**Comment by vikassharmaatl** [comment]
For copilot I have the following scopes: openid profile
For elements.xml I have customScope: api://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SPO.Read

**Comment by adilei** [comment]
You need to populate the same custom scope in Token Exchange URL. Also, you will not be able to use Generative Answers over SharePoint without Files.Read.All and Sites.Read.All

![image](https://github.com/microsoft/CopilotStudioSamples/assets/28257760/a0d548fb-880b-401e-ad77-ed7e2cba4f92)

**Comment by vikassharmaatl** [comment]
Still not working, still looking into it.
This is what I see:
![image](https://github.com/microsoft/CopilotStudioSamples/assets/37592935/9850ee32-9aaa-4256-8a8f-78ef3cd44d37)

**Comment by adilei** [comment]
There is probably a mismatch between your custom scope and the token exchange URL

**Comment by adilei** [comment]
Closed due to inactivity..
