### ISSUE TITLE
Issue: SharePoint SSO Component

### ISSUE THREAD

**Issue by pddiaz123** [microsoft/CopilotStudioSamples#180]
Hi, I was able to build and deploy the SharePoint Webpart as well as the previous sections have been set up.  However, after deploying I am unable to add the app, it says "Sorry, something went wrong with adding the app" but there are no additional details so I'm not sure.  Please advise.  

![2024-03-05_10-08-30](https://github.com/microsoft/CopilotStudioSamples/assets/59672415/d84ce02c-57c6-4636-95d2-dd78521b4dd0)

**Comment by vikassharmaatl** [comment]
I noticed this error when the elements.xml file was corrupted. The file got corrupted when I edited it manually instead of using the python script. I had to restore the original elements.xml and re-ran the python script.

**Comment by pddiaz123** [comment]
Hi, that worked!!  thanks so much!!  I was able to deploy successfully.  But now I'm just getting a "loading" message

![image](https://github.com/microsoft/CopilotStudioSamples/assets/59672415/2d746df0-d602-47f9-99bb-5b606e1df9b3)

**Comment by adilei** [comment]
> Hi, that worked!! thanks so much!! I was able to deploy successfully. But now I'm just getting a "loading" message
> 
> ![image](https://private-user-images.githubusercontent.com/59672415/310282527-2d746df0-d602-47f9-99bb-5b606e1df9b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzQwODQsIm5iZiI6MTcwOTY3Mzc4NCwicGF0aCI6Ii81OTY3MjQxNS8zMTAyODI1MjctMmQ3NDZkZjAtZDYwMi00N2Y5LTk5YmItNWI2MDZlMWRmOWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxMjMwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MGNkZmQ5OWJlMGM3MTc2YjIyMzQ2MjUwMDVmNGY0NjdiNzU0OTI5Yjk2NDAxZWM4NjA0ZGQ0MGY5Y2I4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6W0e9B9Bkk1Yz_uCadFg7fORkPKrz1eEoInCmyKnLQ)

Probably a misconfiguration on your app registration. Can you check for any client side errors in dev tools?

**Comment by vikassharmaatl** [comment]
if you click on the error in dev tools it should show a page with the exact error. In my case it was redirect URIs not configured in the app registrations.

**Comment by pddiaz123** [comment]
I get this error message.
![image](https://github.com/microsoft/CopilotStudioSamples/assets/59672415/0ce85cfa-9142-4135-b43f-975afb494780)

**Comment by pddiaz123** [comment]
I am able to get in!  Yay!  Can we only add a chatbot on one site?  We would have to create separate one for each site if we want it on a few of them for example?

**Comment by pddiaz123** [comment]
Oh it works on the other site I tested with now too, it wasn't initially.  So if we create another bot for the Benefits department for example, we would create a custom SPO app for it as well?

**Comment by adilei** [comment]
Depends, if you want the same custom copilot to work on different sites, add those sites' URLs to your canvas app registration Redirect URIs (step 2 in the guide).

If you want a different copilot altogether (different topics, logic), right now you would have to create a new package, but I am about to introduce a few changes to the repo that will simplify this process.

**Comment by pddiaz123** [comment]
Thank you all!
