### ISSUE TITLE
I've managed to see it on page but it's not doing anything. Opens the canvas and stays in Loading. Any idea what can be wrong ?

### ISSUE THREAD

**Issue by adilei** [microsoft/CopilotStudioSamples#183]
> > Hello, I've managed to see it on page but it's not doing anything. Opens the canvas and stays in Loading. ![image](https://private-user-images.githubusercontent.com/105270821/309805763-0504827d-ce51-4e86-9b10-729576cb1093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjIwMjAsIm5iZiI6MTcwOTYyMTcyMCwicGF0aCI6Ii8xMDUyNzA4MjEvMzA5ODA1NzYzLTA1MDQ4MjdkLWNlNTEtNGU4Ni05YjEwLTcyOTU3NmNiMTA5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwNjU1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjNiNDIwODBlYzM3YjZlNGEyYjdhZGNjZGM2ZGFhODM0Yjc2MWNiZThkZTdjMGMyMWYwYTZmN2UxMDI5NjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E-jwMvrqvCesmlBQTIvi2w5YiaNuzB42rO_hU9pWV_Q) Any idea what can be wrong ?
> 
> Chatted internally - in your case some URIs were missing from Redirect URIs - correct?

Having this same issue where the bot is showing, however, just loading, any suggestions for the possible fix?

_Originally posted by @Penjilia in https://github.com/microsoft/CopilotStudioSamples/issues/175#issuecomment-1992160414_

**Comment by adilei** [comment]
@Penjilia , have a look at Dev tools for any errors. If you are seeing errors around login URLs, follow the URL for a full description of the error

**Comment by Penjilia** [comment]
@adilei no I'm not seeing any errors around Login URLs, I just replied to that as you mentioned it. I followed the guide exactly; the bot is displayed as loading as per the initial screenshot.

**Comment by adilei** [comment]
Are you using dev tools?

**Comment by Penjilia** [comment]
@adilei seeing the following: 
Failed to load resource: the server responded with a status of 400 (Bad Request)
pva-sso-application-customizer_bf024f8d882e21f16822.js:2 ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at t [as constructor] (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1106851)
    at new t (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1112427)
    at t.createEndpointDiscoveryIncompleteError (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1113333)
    at Function.<anonymous> (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1287485)
    at pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1097921
    at Object.throw (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1098026)
    at s (pva-sso-application-customizer_bf024f8d882e21f16822.js:2:1096818)

**Comment by adilei** [comment]
What value do you have for "authority" in elements.xml?

**Comment by Penjilia** [comment]
@adilei for this iteration test i put portal.office.com

**Comment by adilei** [comment]
That's not a valid value. An authority needs to point to your tenant's Entra ID

Have a look here

https://github.com/microsoft/CopilotStudioSamples/blob/master/SharePointSSOComponent/SETUP.md#property-details

You don't have to repackage everything, it's enough to run the PowerShell script with the new value

https://github.com/microsoft/CopilotStudioSamples/blob/master/SharePointSSOComponent/SETUP.md#step-4--upload-the-component-to-sharepoint

**Comment by Penjilia** [comment]
please guide me on what this url would be if my domain name is penjilia.com for example?

**Comment by Penjilia** [comment]
@adilei works now, had to use the specific guid in the url, thank you!
