### ISSUE TITLE
Bot interface just loading.....

### ISSUE THREAD

**Issue by forrman** [microsoft/CopilotStudioSamples#184]
I installed the bot framework and configured it and everything was working perfectly yesterday, but today the interface pops up and is just "loading". I don't see login prompts or anything. Any suggestions here?
![rrbot](https://github.com/microsoft/CopilotStudioSamples/assets/34283224/7f0aca2f-4c94-4c09-b306-537fe19e3a29)

I have uninstalled / reinstalled. Reconfigured several times. I can't tell if there was a pop-up i missed or something else is going on here. 

The chatbot is working correctly on the back-end and no configuration changes have been made to app registrations.

Seems that the token endpoint is not working correctly, even though I took it directly off the mobile channel.
![image](https://github.com/microsoft/CopilotStudioSamples/assets/34283224/55bb171d-ff79-42ba-8283-56d7a8183fbd)

**Comment by adilei** [comment]
WDYM bot framework? Are you not using Copilot Studio?

Can you share the full token endpoint for your bot/copilot from element.xml?

**Comment by forrman** [comment]
https://defaultb39bc2dae3c84f92960e4151a1ae16.ad.environment.api.powerplatform.com/powervirtualagents/botsbyschema/cre46_researchBot/directline/token?api-version=2022-03-01-preview @adilei

**Comment by adilei** [comment]
Yep, I can see the error. It's not the SSO component, it's your bot. I'm not sure, but they may have been an update that disrupted some services today. Can you check with customer support?

**Comment by forrman** [comment]
That bot is definitely acting funky today - i keep getting error messages in it like this one, so maybe it's just that. Thank you!
![image](https://github.com/microsoft/CopilotStudioSamples/assets/34283224/9544832b-a1a4-45e4-8bb1-f799947158c7)
