### ISSUE TITLE
Issue: SharePoint SSO Component

### ISSUE THREAD

**Issue by rod-stagg-seagen** [microsoft/CopilotStudioSamples#192]
Is it possible to pass input parameters to the SSO component e.g. from a search box on the same SharePoint page?

**Comment by adilei** [comment]
Can you elaborate on the use case? What sort of flow do you have in mind?

**Comment by rod-stagg-seagen** [comment]
Yes, we have developed an enterprise search tool hosted on SharePoint Online and would like to add generative AI capabilities to our search box e.g. based on a keyword input into the search box return generative AI responses.

**Comment by adilei** [comment]
Got it. Sharing parameters with the custom copilot component does not seem like a good pattern for this. I would suggest connecting your back-end to a service such as Azure OpenAI on your data.
