### ISSUE TITLE
Can this component be used for a SharePoint 2016 site that is hosted on a non-Azure cloud platform or on-premise 

### ISSUE THREAD

**Issue by jasy2018** [microsoft/CopilotStudioSamples#200]
Thank you for developing this component which i believe is useful for SharePoint Online sites. However, my organisation SharePoint sites are not hosted on SharePoint Online but on SharePoint 2016 and they are either on-premise or on a non-Azure cloud platform, e.g. AWS. Would like to check if this component can be used for such sites and if yes, are there documentation on how this can be done. 

Thanking in advance for any help offered!!

**Comment by adilei** [comment]
I don't think so - this component is an extension, and extensions aren't supported for 2016: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/compatibility
