### ISSUE TITLE
Issue: SharePoint SSO Component I am losing my citations/references in the response

### ISSUE THREAD

**Issue by pm38702003** [microsoft/CopilotStudioSamples#201]
maybe this is more of a question for "botframework-webchat" but i am losing my citations/references in the return message. The urls and text are clearly in the activity.Text bit get lost somewhere

**Comment by pm38702003** [comment]
needed a delimiter in the markdown

**Comment by lifan0127** [comment]
Hello @pm38702003 could you please explain how it worked out for you?
