### ISSUE TITLE
SSL Certificate problem

### ISSUE THREAD

**Issue by RyanNewmanTruGreen** [microsoft/CopilotStudioSamples#216]
**What sample tool are you using?**
Issue starts with cloning the repository

**Describe the bug**
A message populates: "Git: Fatal: Unable to access 'https://Github.com/Microsoft/CopilotStudioSamples.git/': SSL certificate problem: self-signed certificate in certificate chain"

**To Reproduce**
1. Go to https://github.com/microsoft/CopilotStudioSamples.git
2. Click on 'Clone' / copy Url
3. Open Visual Studio Code / Visual Studio 2022
4. See error mentioned above

**Expected behavior**
Repository should clone/download into either Visual Studio Code or Visual Studio 2022 without this error message.

**Screenshots**
![image](https://github.com/microsoft/CopilotStudioSamples/assets/108489169/455e1293-a20f-4499-9d76-c182a3f074ba)

**Additional context**
No additional context.

**Comment by adilei** [comment]
Can you make sure it's not a local proxy/firewall that is terminating traffic and using its own certificate to encrypt?

**Comment by RyanNewmanTruGreen** [comment]
Hi Adilei,

Thanks for reaching out. I found that instead of cloning the repository, downloading as a zip file and opening it manually into Visual Studio Code worked for me.


Thank You,
Ryan Newman
Application Developer II
***@***.***
