### ISSUE TITLE
[Implementation Guide] Password for ServiceNow Instance not working

### ISSUE THREAD

**Issue by myfope** [microsoft/CopilotStudioSamples#232]
Within the document Lab 03 - Build and Invoke Power Automate cloud flows.docx there is a password provided for the Service Now instance. This password (or the user account) seems to no longer work. Can you update the documentation accordingly so that we can build this on our own?

**Comment by HenryJammes** [comment]
Hi @myfope, thanks!
This is actually expected, check out the proctor instructions to setup your own ServiceNow environment for this lab (or just use a static payload as a response back from Power Automate to Copilot Studio)
