### ISSUE TITLE
Issue: SharePoint SSO Component - CORS error

### ISSUE THREAD

**Issue by samrutur** [microsoft/CopilotStudioSamples#235]
When I launch the SharePoint component, I get the error message below. It looks there is a CORS issue. How to resolve this? I  updated the origin to use the site url where this is used. I can access from demo web site with the code that is sent from the sign in button.
![image](https://github.com/user-attachments/assets/8ccb5ce8-4ade-4f6d-b720-52c82c32cbcf)

**Comment by adilei** [comment]
This looks like a misconfiguration - you shouldn't be fetching information from there. Use the token endpoint: https://learn.microsoft.com/en-us/microsoft-copilot-studio/publication-connect-bot-to-custom-application#retrieve-your-copilot-studio-copilot-parameters

**Comment by samrutur** [comment]
Thank you! That was it.
